config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flats
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <h1>Add a new Flat</h1>
  <%= simple_form_for(flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit %>
  <% end %>
</div>

app/views/flats/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand">Simple Airbnb</a>
    <form class="d-flex" role="search">
      <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary" %>
    </form>
  </div>
</nav>

app/views/flats/index.html.erb
<%= render 'navbar' %>


<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <%= render 'flat', flat: flat %>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render 'navbar' %>

<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<%= render 'navbar' %>

<div class="card">
<h1><%= @flat.name %></h1>
<p><%= @flat.address %></p>
</div>


<div class="card">
<h2>A bit more about this flat...</h2>
<p><%= @flat.description %></p>
</div>


<div class="Card">
  <h2>Book this place!</h2>
  <%= form_with do |form| %>
    <p>From: <%= form.date_field :born_on %></p>
    <p>To: <%= form.date_field :born_on %></p>
  <% end %>
  <button type="button" class="btn btn-success">Book</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>